# @package _global_
name: &name LinearGaussian
log_level: INFO

forward_dynamics:
  A: &A [[0.8990]]
  Q: &Q [[1.2858]]
  C: &C [[0.6941]]
  R: &R [[0.3740]]

sim:
  _target_: src.sim.linear_gaussian_sim.ReverseSimulation
  env:
    _target_: src.steppers.env_stepper.EnvStepper
    inner_env:
      _target_: src.envs.env.StateSpaceEnv
      prior_policy: &prior
        _target_: src.policies.linear_gaussian_policies.GaussianPolicy
        dim: &dim 1
        A: *A
        Q: *Q
      num_particles: &num_particles 10
      dim: *dim
      likelihood:
        _target_: src.likelihoods.likelihoods.LinearGaussianLikelihood
        C: *C
        R: *R
      time_limit: &time_limit 500
      ess_threshold: 0.9
      resampler:
        _target_: src.resamplers.NoResampler
      train: False
    recorder:
      _target_: ${get_recorder:${sim._target_}}
      num_particles: *num_particles
    steppers:
      - visualizer:
        _target_: src.steppers.visualizers.estimator_variance_visualizer.EstimatorVarianceVisualizer
        name: "SmoothingEstimatorVariance"
        title: "Variance of Smoothing Estimator"
  proposal_policy:
    _target_: src.policies.linear_gaussian_policies.OptimalSmoothingPolicy
    A: *A
    C: *C
    Q: *Q
    R: *R
